languageCode = "en-us"
languageName = "English"
weight = 1
title = "AskBlueCat"
description = "Offensive and Defensive Ops"

[params]
displayName = "EN"
logo = "ABC.png"
description = "Offensive and Defensive Ops"
rtl = false
dateFormat = "16 January 2026"

["params.author"]
name = "ABC"
email = "mthu779@proton.me"
image = "NagarPhaYar.png"
bio = "hi,friends. This is h0n3yp00p. Ready to explore into the unknown? "
