[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Writeups"
  pageRef = "writeups"
  weight = 20

[[main]]
  name = "English"
  params = { displayName = "EN" }
  weight = 30
