[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Writeups"
  pageRef = "writeups"
  weight = 20

[[main]]
  name = "English"
  params = { displayName = "EN" }
  weight = 30

[[main]]
  name = "Buy Me a Coffee"
  url = "https://www.buymeacoffee.com/your_username"
  weight = 40
  pre = "<span class='relative block icon'><svg ...></svg></span>" # Optional icon
