colorScheme = "blowfish"

defaultAppearance = "dark"

[header]

  layout = "basic"

  showLanguageSwitcher = true

  logo = "img/ABC.png" # Path relative to 'static'

[homepage]

  layout = "background" # Matches the demo splash style

  homepageImage = "img/hacktheboxBG.jpg" # The demo's diagonal lines

  showRecent = true

  showRecentItems = 5

[article]

  showReadingTime = true

  showTableOfContents = true
