colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

[header]
layout = "basic"
showLanguageSwitcher = true
logo = "img/ABC.png"

[homepage]
layout = "background"
homepageImage = "img/background.jpg"
showRecent = true
showRecentItems = 5

[assets]
  favicon = "favicon.ico"
  favicon16 = "favicon-16x16.png"
  favicon32 = "favicon-32x32.png"
  appleTouchIcon = "apple-touch-icon.png"

[article]
showReadingTime = true
showTableOfContents = true

[author]
  name = "ABC"
  image = "author.png"
  headline = "Cybersecurity Researcher"
  bio = "Fresh prints in the snow!"

[buymeacoffee]
identifier = ""
